### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by deonthomasgy** [Lamesya/freshdesk#4]
Hi Lamesya,

Can you say if this module can be used to create tickets and retrieve the tickets back based on email address.

I would like to create an "in-app" ticket system where customer can make a report and in the app when we respond in freshdesk, they get to see an update in the "in app - inbox"

**Comment by Lamesya** [comment]
Hi @deonthomasgy,

This is still underdeveloped and it might create some issue.

Current function it has is to view and list the tickets, other than that is in progress.

**Comment by deonthomasgy** [comment]
ok, we're looking to had in our app the listing of tickets, the ability to view ticket and create. I understand that you don't have the create part as yet. Can we support you in anyway to get the create feature working?
